# Generated by Django 4.1.5 on 2023-01-18 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=32)),
                ('account_creation_date', models.DateField(default=django.utils.timezone.now)),
                ('profile_description', models.TextField()),
            ],
        ),
    ]
